name: Build App and Package Source Code

on:
  push:
    branches:
      - main  # 当 push 代码到 main 分支时触发

jobs:
  archive:
    runs-on: ubuntu-latest # 在 GitHub 的 Ubuntu 虚拟机上运行

    steps:
      # 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26' # 改为你的 Go 语言版本

      # 交叉编译为 Linux 64位 二进制文件
      - name: Build Go Application
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o acgn-at-anyone main.go

      # 打包二进制程序与配置文件
      - name: Compress App binaries
        run: |
          # 压缩二进制和配置为 zip
          zip acgn-at-anyone.zip acgn-at-anyone config.yaml
          
          # 压缩二进制和配置为 tar.gz
          tar -czf acgn-at-anyone.tar.gz acgn-at-anyone config.yaml

      # 使用 git archive 干净地打包项目源码（同时生成 zip 和 tar.gz）
      - name: Compress Source Code
        run: |
          # 打包源码为 zip
          git archive --format=zip -o source_code.zip HEAD
          
          # 打包源码为 tar.gz
          git archive --format=tar.gz -o source_code.tar.gz HEAD

      # 将所有生成的四个压缩包上传到服务器的指定目录
      - name: Upload archives to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          # 传输生成的 4 个压缩包文件
          source: "acgn-at-anyone.zip,acgn-at-anyone.tar.gz,source_code.zip,source_code.tar.gz"
          target: ${{ secrets.SERVER_DIR }}           # 更改为你服务器上用来存放压缩包的【目标目录】
          overwrite: true                  # 允许覆盖同名旧文件